// le fichier layout joue un rôle important dans la structuration et la mise en page de votre application. Il s'agit d'un composant React réutilisable qui enveloppe le contenu de vos pages pour fournir une mise en page cohérente à travers l'ensemble de votre application.A savoir:

// Vous pouvez créer un fichier layout dans votre répertoire components ou tout autre répertoire où vous stockez vos composants réutilisables.Une fois que vous avez créé votre layout, vous pouvez l'utiliser dans vos pages en l'important et en l'enveloppant autour du contenu de la page. Vous pouvez personnaliser votre layout en ajoutant des composants réutilisables tels que des en-têtes, des pieds de page, des barres de navigation, etc. Vous pouvez également utiliser des outils de style tels que CSS, Sass ou Styled Components pour styliser votre layout.Vous pouvez également gérer dynamiquement le contenu du layout en passant des props ou en utilisant le contexte React pour fournir des fonctionnalités supplémentaires aux composants enveloppés dans le layout. 

import './index.css'
import Navigation from "@/components/Navigation"
import Footer from "@/components/Footer"

// cette variable exporte simplement un objet contenant des métadonnées pour une page ou une application. Les métadonnées incluses sont le titre (title) et la description (description).

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}


// La fonction RootLayout est un composant React qui définit une structure de base pour une page HTML. Elle est exportée par défaut, ce qui signifie qu'elle peut être utilisée comme composant principal dans d'autres parties de votre application. Elle prend un seul argument destructuré, children, qui représente le contenu que vous souhaitez encapsuler dans la structure HTML de base.

// À l'intérieur de la fonction RootLayout, le contenu encapsulé par la balise <body> est représenté par la prop children. Cela signifie que tout ce que vous passez à RootLayout en tant qu'enfant sera rendu à cet endroit précis dans la structure HTML. 

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
        <Footer />
        </body>
    </html>
  )
}
